### ISSUE TITLE
Router doesn't work if no trailing slash

### ISSUE THREAD

**Issue by iamdriz** [phpgearbox/router#5]
I've asked it here instead: http://stackoverflow.com/questions/36495991/laravel-router-picks-wrong-route-if-no-trailing-slash

**Comment by brad-jones** [comment]
Hi @iamdriz,

I havn't used this for ages, Laravel has moved on, this code is based on Laravel 4.x.
There are much better alternatives now plus with things like PSR-7 Middleware you can do so much more.

If you are looking for a standalone router component, I would strongly suggest looking at something like http://route.thephpleague.com/ or even just using https://github.com/nikic/FastRoute directly.

If you do come up with a fix though, feel free to send me a PR & I'll get it merged for you.

Cheers Brad
